name: utopic_tor_onion_proxy
description: Flutter Plugin for Android, based on Android library that start Tor Onion Proxy on random local socket.
version: 0.1.0
homepage: https://github.com/utopicnarwhal/utopic_tor_onion_proxy

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ru.utopicnarwhal.utopic_tor_onion_proxy
        pluginClass: UtopicTorOnionProxyPlugin
      ios:
        pluginClass: UtopicTorOnionProxyPlugin
